# Generated by Django 4.0.6 on 2022-07-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('otp', models.IntegerField(default=9999)),
                ('subscribed', models.BooleanField(default=0)),
            ],
        ),
    ]
